language: go

go:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
    - $HOME/gopath/bin/goveralls -repotoken lUHF0MSdZFIAeqBLYLtUfQiw5aIzyhp7O